"""remove screenshot path from tickets

Revision ID: 1de5c8a22e80
Revises: 6e51c78afe27
Create Date: 2026-09-09 15:17:37.434727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1de5c8a22e80'
down_revision: Union[str, Sequence[str], None] = '6e51c78afe27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'screenshot_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('screenshot_path', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
